//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrantsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesLog
    {
        public int UpdateLogID { get; set; }
        public int BaseLogID { get; set; }
        public int ObjectID { get; set; }
        public string ObjectType { get; set; }
        public string State { get; set; }
    
        public virtual LogsBase LogsBase { get; set; }
    }
}
