//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace EntrantsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Entrant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrant()
        {
           
            this.CertificateMarks = new List<CertificateMark>();
            this.TestMarks = new List<TestMark>();
        }
       
        public int EntrantID { get; set; }        
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronumic { get; set; }
        public int CityID { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public Nullable<int> Entrance { get; set; }
        public int Flat { get; set; }
    
        public HashSet<int> mySet { get; set; }
        public ICollection<int> ls => new List<int>(new int[] { 1, 2, 3 }); 
        public IEnumerable<int> sldjf { get; set; }
        public List<int> l { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<CertificateMark> CertificateMarks { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<TestMark> TestMarks { get; set; }
    }
}
