//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrantsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionLogID { get; set; }
        public int BaseLogID { get; set; }
        public string ExceptionType { get; set; }
        public string StackTrace { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
    
        public virtual LogsBase LogsBase { get; set; }
    }
}
