//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrantsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public int SpecialityID { get; set; }
        public int FacultyID { get; set; }
        public string Title { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
