//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSetting
    {
        public int ApplicationSettingsID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> ApplicationGroupID { get; set; }
        public Nullable<int> NextGroupID { get; set; }
        public Nullable<int> NumberOfMainGroupSpecialities { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
