//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupFriendship
    {
        public int GroupFriendshipID { get; set; }
        public int RequestingGroupID { get; set; }
        public int AccessibleGroupID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
