//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntermediatePaymentOption
    {
        public int IntermediatePaymentOptionID { get; set; }
        public int PaymentOptionID { get; set; }
        public int PaymentTypeID { get; set; }
    
        public virtual PaymentOption PaymentOption { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
