//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileSubjectsGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileSubjectsGroup()
        {
            this.SpecialityApplications = new HashSet<SpecialityApplication>();
        }
    
        public int ProfileSubjectsGroupID { get; set; }
        public int SpecialityTestOptionID { get; set; }
        public int SpecialitySubjectID { get; set; }
        public int Rang { get; set; }
    
        public virtual SpecialitySubject SpecialitySubject { get; set; }
        public virtual SpecialityTestOption SpecialityTestOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialityApplication> SpecialityApplications { get; set; }
    }
}
