//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileSubjectsGroup
    {
        public int ProfileSubjectGroupID { get; set; }
        public int SpecialitySubjectID { get; set; }
        public int SpecialityTestOptionID { get; set; }
        public int Rang { get; set; }
    
        public virtual SpecialityTestOption SpecialityTestOption { get; set; }
        public virtual SpecialitySubject SpecialitySubject { get; set; }
    }
}
