//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialityCapacityTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecialityCapacityTable()
        {
            this.UniversitySpecialities = new HashSet<UniversitySpeciality>();
        }
    
        public int SpecialityCapacityID { get; set; }
        public int TotalNumberOfPlaces { get; set; }
        public int TotalNumberOfPaidPlaces { get; set; }
        public int TotalNumberOfFreePayingPlaces { get; set; }
        public int CurrnetNumberOfPlaces { get; set; }
        public int CurrentNumberOfPaidPlaces { get; set; }
        public int CureentNumberOfFreePayingPlaces { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversitySpeciality> UniversitySpecialities { get; set; }
    }
}
