//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialityApplication
    {
        public int SpecialityApplicationID { get; set; }
        public int SpecialityID { get; set; }
        public int ApplicationID { get; set; }
        public int StudyFormTypeID { get; set; }
        public int ProfileSubjectsGroupID { get; set; }
        public Nullable<int> OptionalSubjectID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ProfileSubjectsGroup ProfileSubjectsGroup { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual SpecialitySubject SpecialitySubject { get; set; }
        public virtual StudyFormType StudyFormType { get; set; }
    }
}
