//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversitySpeciality
    {
        public int UniversitySpecialityID { get; set; }
        public int SpecialityID { get; set; }
        public int GroupID { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime ExpiringDate { get; set; }
        public int ColorID { get; set; }
        public int PaymentOptionID { get; set; }
        public int StudyFormOptionID { get; set; }
        public int SpecialityTestOptionID { get; set; }
        public int SpecialityCapacityID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Group Group { get; set; }
        public virtual PaymentOption PaymentOption { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual SpecialityCapacityTable SpecialityCapacityTable { get; set; }
        public virtual SpecialityTestOption SpecialityTestOption { get; set; }
        public virtual StudyFormOption StudyFormOption { get; set; }
    }
}
